version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      /bin/sh -c 'python manage.py wait_for_db &&
                  python manage.py migrate && 
                  python manage.py runserver 0.0.0.0:8000
                  '
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  web:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    command: >
      /bin/sh -c 'cd frontend &&
                  npm install &&
                  npm run serve -- --host 0.0.0.0 --port 8080
                  '


volumes:
  dev-db-data:

